# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nestjs-hello-world

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://webappyulong.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f89423b268ec450087ec819a35248a25 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cada610bfa27406c8e4c355108a3dfc7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: webappyulong.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f89423b268ec450087ec819a35248a25 }}/webappyulong/nestjs-hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nestjs-hello-world'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9aad933adc01453a8091bf1d0a644112 }}
        images: 'webappyulong.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f89423b268ec450087ec819a35248a25 }}/webappyulong/nestjs-hello-world:${{ github.sha }}'