# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nestjs6-web-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://komatsu.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4ae2fe7be9364d12862abbd805a15896 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_785078fd456648cfb20f71ca482dd5d1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: komatsu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4ae2fe7be9364d12862abbd805a15896 }}/hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nestjs6-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8ae68c607a394574b65cbf60cd567150 }}
        images: 'komatsu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4ae2fe7be9364d12862abbd805a15896 }}/hello-world:${{ github.sha }}'