# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - komatsu-webapp-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://komatsu.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1fc9b80234424a1fb35d69abaf4e00a4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8fe6958cbba2445bbced1fce3c78d377 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: komatsu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1fc9b80234424a1fb35d69abaf4e00a4 }}/hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'komatsu-webapp-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2aa20cc3e0b8460896e8a7b5e473277f }}
        images: 'komatsu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1fc9b80234424a1fb35d69abaf4e00a4 }}/hello-world:${{ github.sha }}'