# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - komatsu-web-test-2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://komatsu.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c864f79e0bf44a6b9c173a8c221fc400 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_06b616313dc540829e0d07dc29340194 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: komatsu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c864f79e0bf44a6b9c173a8c221fc400 }}/hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'komatsu-web-test-2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_63aa1e0d0f7942d5992f35acd871793b }}
        images: 'komatsu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c864f79e0bf44a6b9c173a8c221fc400 }}/hello-world:${{ github.sha }}'