# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nestjs-hello-world

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://webappyulong.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_925d7932a4b145c0aa87f84e142c67e7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_98808a6852ab43c68dcbb443cd89c612 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: webappyulong.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_925d7932a4b145c0aa87f84e142c67e7 }}/nestjs-hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nestjs-hello-world'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d0a9df554ab94b4da6c97261ee6c5dcb }}
        images: 'webappyulong.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_925d7932a4b145c0aa87f84e142c67e7 }}/nestjs-hello-world:${{ github.sha }}'