# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nestjs6-web-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://komatsu.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6fda7a4fd12e46b7926550c48a5a44ee }}
        password: ${{ secrets.AzureAppService_ContainerPassword_24607862fd264870a12f8b38f9d37c3e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: komatsu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6fda7a4fd12e46b7926550c48a5a44ee }}/hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nestjs6-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d70eca037a1245d8a93db3c57593a2de }}
        images: 'komatsu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6fda7a4fd12e46b7926550c48a5a44ee }}/hello-world:${{ github.sha }}'