name: Trigger auto deployment for webapp-komatsu-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/webapp-komatsu-test-AutoDeployTrigger-b04f3524-4942-4560-a09e-5c4e783469cd.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WEBAPPKOMATSUTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBAPPKOMATSUTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBAPPKOMATSUTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: komatsu.azurecr.io
          registryUsername: ${{ secrets.WEBAPPKOMATSUTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBAPPKOMATSUTEST_REGISTRY_PASSWORD }}
          containerAppName: webapp-komatsu-test
          resourceGroup: komatsu-dx-app
          imageToBuild: komatsu.azurecr.io/webapp-komatsu-test:${{ github.sha }}
          dockerfilePath: Dockerfile


